import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Observatório Test",
    description: "Generated by create next app",
    authors: [{name: "Charllys de Lima"}],
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 dark:bg-gray-700`}
        >
        {children}
        </body>
        </html>
    );
}
